# Generated by Django 5.1.2 on 2024-11-01 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50)),
                ('col_name', models.CharField(max_length=30)),
                ('col_type', models.CharField(choices=[('object', 'String'), ('uint8', 'Unsigned 8 bit Integer'), ('uint16', 'Unsigned 16 bit Integer'), ('uint32', 'Unsigned 32 bit Integer'), ('uint64', 'Unsigned 64 bit Integer'), ('int8', 'Signed 8 bit Integer'), ('int16', 'Signed 16 bit Integer'), ('int32', 'Signed 32 bit Integer'), ('int64', 'Signed 64 bit Integer'), ('float32', '32 bit Floating Number'), ('float64', 'Float64'), ('bool', 'Boolean')], max_length=10)),
            ],
            options={
                'indexes': [models.Index(fields=['file_id', 'col_name'], name='api_tableco_file_id_93f0d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='GenericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveBigIntegerField()),
                ('string_value', models.CharField(max_length=100)),
                ('int_sign', models.SmallIntegerField()),
                ('uint_value', models.PositiveBigIntegerField()),
                ('double_value', models.FloatField()),
                ('timestamp_value', models.TimeField()),
                ('time_zone_value', models.CharField(max_length=50)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tablecol')),
            ],
            options={
                'indexes': [models.Index(fields=['column', 'row'], name='api_generic_column__08614c_idx')],
            },
        ),
    ]
