# Generated by Django 5.1.2 on 2024-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50)),
                ('col_name', models.CharField(max_length=30)),
                ('col_type', models.CharField(choices=[('STR', 'string'), ('D', 'date'), ('DT', 'datetime'), ('DTZ', 'datetimezone'), ('U8', 'uint8'), ('U16', 'uint16'), ('U32', 'uint32'), ('U64', 'uint64'), ('I8', 'int8'), ('I16', 'int16'), ('I32', 'int32'), ('I64', 'int64'), ('F32', 'float32'), ('F64', 'float64'), ('BOOL', 'bool')], max_length=20)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'indexes': [models.Index(fields=['file_id', 'col_name'], name='api_generic_file_id_2a85ea_idx')],
            },
        ),
    ]
