# Generated by Django 5.1.2 on 2024-11-01 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_api_generic_column__08614c_idx_generic_dat_column__3cc1b5_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='genericdata',
            new_name='api_generic_column__e3f041_idx',
            old_name='generic_dat_column__3cc1b5_idx',
        ),
        migrations.RenameIndex(
            model_name='tablecol',
            new_name='api_table_c_file_id_bf7eec_idx',
            old_name='table_col_file_id_ad29af_idx',
        ),
        migrations.AlterModelTable(
            name='genericdata',
            table='api_generic_data',
        ),
        migrations.AlterModelTable(
            name='tablecol',
            table='api_table_col',
        ),
    ]
