# Generated by Django 5.1.2 on 2024-11-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0003_rename_generic_dat_column__3cc1b5_idx_api_generic_column__e3f041_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="genericdata",
            old_name="int_sign",
            new_name="int_sign_value",
        ),
        migrations.RemoveField(
            model_name="genericdata",
            name="time_zone_value",
        ),
        migrations.RemoveField(
            model_name="genericdata",
            name="timestamp_value",
        ),
        migrations.AddField(
            model_name="genericdata",
            name="datetime_value",
            field=models.DateTimeField(default="2022-09-27 18:00:00.000"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="genericdata",
            name="time_zone_info_value",
            field=models.CharField(default="hola", max_length=30),
            preserve_default=False,
        ),
    ]
