# Generated by Django 5.1.2 on 2024-11-01 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50)),
                ('col_name', models.CharField(max_length=30)),
                ('col_type', models.CharField(choices=[('object', 'String'), ('uint8', 'Unsigned 8 bit Integer'), ('uint16', 'Unsigned 16 bit Integer'), ('uint32', 'Unsigned 32 bit Integer'), ('uint64', 'Unsigned 64 bit Integer'), ('int8', 'Signed 8 bit Integer'), ('int16', 'Signed 16 bit Integer'), ('int32', 'Signed 32 bit Integer'), ('int64', 'Signed 64 bit Integer'), ('float32', '32 bit Floating Number'), ('float64', 'Float64'), ('bool', 'Boolean')], max_length=10)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='genericdata',
            name='api_generic_file_id_2a85ea_idx',
        ),
        migrations.RemoveField(
            model_name='genericdata',
            name='col_name',
        ),
        migrations.RemoveField(
            model_name='genericdata',
            name='col_type',
        ),
        migrations.RemoveField(
            model_name='genericdata',
            name='file_id',
        ),
        migrations.RemoveField(
            model_name='genericdata',
            name='value',
        ),
        migrations.AddField(
            model_name='genericdata',
            name='double_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='int_sign',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='row',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='string_value',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='time_zone_value',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='timestamp_value',
            field=models.TimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericdata',
            name='uint_value',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='tablecol',
            index=models.Index(fields=['file_id', 'col_name'], name='api_tableco_file_id_93f0d4_idx'),
        ),
        migrations.AddField(
            model_name='genericdata',
            name='column',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.tablecol'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='genericdata',
            index=models.Index(fields=['column', 'row'], name='api_generic_column__08614c_idx'),
        ),
    ]
