# Generated by Django 5.1.2 on 2024-11-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genericdata_bool_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecol',
            name='col_index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
