# Generated by Django 5.1.2 on 2024-11-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tablecol_col_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tablecol',
            name='api_table_c_file_id_bf7eec_idx',
        ),
        migrations.AddIndex(
            model_name='tablecol',
            index=models.Index(fields=['file_id', 'col_index'], name='api_table_c_file_id_1b17ca_idx'),
        ),
    ]
