services:
  rhombus-back:
    image: rhombus-back
    container_name: rhombus-back
    build:
      context: .
      dockerfile: Dockerfile
    # command: tail /dev/null -f
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app/backend/
      - ./api/:/app/api/
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - rhombus-network

networks:
  rhombus-network:
    driver: bridge
    name: rhombus-network
